import { Goal, adjustGoals } from "./common";

export const AlphaBounceGoalNames = [
  'planets',
  'earth',
  'mission',
  'map',
  'escorp',
  'furi',
] as const;

export type AlphaBounceGoalName = typeof AlphaBounceGoalNames[number];

export const AlphaBounceGoals: Record<AlphaBounceGoalName, Goal> = {
  planets: {
    id: 'planets',
    name: {
      en: 'Planètes explorées',
      fr: 'Planètes explorées',
      de: 'Erkundete Planeten',
      es: 'Planètes explorées',
    },
    rare: 0,
    unlocks: [
      { count: 1, points: 10, icon: 'small_forum_read.gif' },
      { count: 2, points: 10 },
      { count: 3, points: 10 },
      { count: 4, points: 10 },
      { count: 5, points: 10 },
      { count: 6, points: 10 },
      { count: 7, points: 10 },
      { count: 8, points: 10 },
      { count: 9, points: 10 },
      { count: 10, points: 10 },
      { count: 11, points: 10 },
      { count: 12, points: 10 },
      { count: 13, points: 10 },
      { count: 14, points: 10 },
      { count: 15, points: 10, icon: 'small_forum.gif' },
      { count: 16, points: 10 },
      { count: 17, points: 10 },
      { count: 18, points: 10 },
      { count: 19, points: 10 },
      { count: 20, points: 10 },
      { count: 21, points: 10 },
    ],
  },
  earth: {
    id: 'earth',
    name: {
      en: 'Terre retrouvée',
      fr: 'Terre retrouvée',
      de: 'Wieder auf der Erde',
      es: 'Terre retrouvée',
    },
    rare: 0,
    unlocks: [
      {
        count: 1,
        points: 10,
        icon: 'small_earth.gif',
        title: {
          en: 'Terre !',
          fr: 'Terre !',
          de: 'Die Erde!',
          es: 'Terre !',
        },
      },
    ],
  },
  mission: {
    id: 'mission',
    name: {
      en: 'missions accomplies',
      fr: 'missions accomplies',
      de: 'Erledigte Missionen',
      es: 'missions accomplies',
    },
    rare: 1,
    unlocks: [
      { count: 1, points: 10 },
      { count: 2, points: 10 },
      { count: 3, points: 10, icon: 'small_fuel_free.gif' },
      { count: 4, points: 10 },
      { count: 5, points: 10 },
      { count: 6, points: 10 },
      { count: 7, points: 10 },
      { count: 8, points: 10 },
      { count: 9, points: 10 },
      { count: 10, points: 10, icon: 'small_bricks.gif' },
      { count: 11, points: 10 },
      { count: 12, points: 10 },
      { count: 13, points: 10 },
      { count: 14, points: 10 },
      { count: 15, points: 10 },
      { count: 16, points: 10 },
      { count: 17, points: 10 },
      { count: 18, points: 10 },
      { count: 19, points: 10 },
      { count: 20, points: 10 },
      { count: 21, points: 10 },
      { count: 22, points: 10 },
      { count: 23, points: 10 },
      { count: 24, points: 10 },
      { count: 25, points: 10 },
      { count: 26, points: 10 },
      { count: 27, points: 10 },
      { count: 28, points: 10 },
      { count: 29, points: 10 },
      { count: 30, points: 10, icon: 'small_fuel.gif' },
      { count: 31, points: 10 },
      { count: 32, points: 10 },
      { count: 33, points: 10 },
      { count: 34, points: 10 },
      { count: 35, points: 10 },
      { count: 36, points: 10 },
      { count: 37, points: 10 },
      { count: 38, points: 10 },
    ],
  },
  map: {
    id: 'map',
    name: {
      en: 'niveaux réussis',
      fr: 'niveaux réussis',
      de: 'Fortschritt',
      es: 'niveaux réussis',
    },
    rare: 0,
    unlocks: [
      {
        count: 10,
        points: 3,
        title: {
          en: 'That\'s one small step for a man...',
          fr: 'That\'s one small step for a man...',
          de: 'Ein kleiner Schritt für mich...',
          es: 'That\'s one small step for a man...',
        },
      },
      {
        count: 100,
        points: 3,
        title: {
          en: 'Houston, we have a problem',
          fr: 'Houston, we have a problem',
          de: 'Houston, wir haben ein Problem',
          es: 'Houston, we have a problem',
        },
      },
      {
        count: 1000,
        points: 3,
        title: {
          en: 'Il fait noir, par ici.',
          fr: 'Il fait noir, par ici.',
          de: 'Es ist so dunkel hier.',
          es: 'Il fait noir, par ici.',
        },
      },
      {
        count: 10000,
        points: 3,
        title: {
          en: '\'Coucou Laïka, il te reste des croquettes ?\'',
          fr: '\'Coucou Laïka, il te reste des croquettes ?\'',
          de: 'Laika, bist du bereit Gassi zu gehen?',
          es: '\'Coucou Laïka, il te reste des croquettes ?\'',
        },
      },
      {
        count: 100000,
        points: 3,
        title: {
          en: 'L\'univers infini, j\'en ai fait le tour !',
          fr: 'L\'univers infini, j\'en ai fait le tour !',
          de: 'Einmal Universum und zurück bitte!',
          es: 'L\'univers infini, j\'en ai fait le tour !',
        },
      },
    ],
  },
  escorp: {
    id: 'escorp',
    name: {
      en: 'Grade ESCORP atteint',
      fr: 'Grade ESCORP atteint',
      de: 'Dienstgrad ESCORP',
      es: 'Grade ESCORP atteint',
    },
    rare: 1,
    unlocks: [
      { count: 1, points: 5, icon: 'rank_1.gif' },
      { count: 2, points: 5, icon: 'rank_2.gif' },
      { count: 3, points: 5, icon: 'rank_3.gif' },
      { count: 4, points: 5, icon: 'rank_4.gif' },
      { count: 5, points: 5, icon: 'rank_5.gif' },
      { count: 6, points: 5, icon: 'rank_6.gif' },
      { count: 7, points: 5, icon: 'rank_7.gif' },
      { count: 8, points: 5, icon: 'rank_8.gif' },
      { count: 9, points: 5, icon: 'rank_9.gif' },
      { count: 10, points: 5, icon: 'rank_10.gif' },
      { count: 11, points: 5, icon: 'rank_11.gif' },
      { count: 12, points: 5, icon: 'rank_12.gif' },
    ],
  },
  furi: {
    id: 'furi',
    name: {
      en: 'Grade FURI atteint',
      fr: 'Grade FURI atteint',
      de: 'Dienstgrad FURI',
      es: 'Grade FURI atteint',
    },
    rare: 1,
    unlocks: [
      { count: 1, points: 5, icon: 'rank_furi_1.gif' },
      { count: 2, points: 5, icon: 'rank_furi_2.gif' },
      { count: 3, points: 5, icon: 'rank_furi_3.gif' },
      { count: 4, points: 5, icon: 'rank_furi_4.gif' },
      { count: 5, points: 5, icon: 'rank_furi_5.gif' },
      { count: 6, points: 5, icon: 'rank_furi_6.gif' },
      { count: 7, points: 5, icon: 'rank_furi_7.gif' },
      { count: 8, points: 5, icon: 'rank_furi_8.gif' },
      { count: 9, points: 5, icon: 'rank_furi_9.gif' },
      { count: 10, points: 5, icon: 'rank_furi_10.gif' },
      { count: 11, points: 5, icon: 'rank_furi_11.gif' },
      { count: 12, points: 5, icon: 'rank_furi_12.gif' },
    ],
  },
};

export const AlphaBounceAdjustedGoals = adjustGoals(AlphaBounceGoals);